public class Constants {
    public static final String EMAIL_ENCODING_KEY = 'UTF-8';
    public static final String TIME_ZONE_SID_KEY = 'America/Los_Angeles';
    //public static final String LOCALE_SID_KEY = 'en_US';
    //public static final String LANGUAGE_LOCALE_KEY = 'en_US';
    public static final String PORTAL_USERNAME_SUFFIX = 'sfdx.portal';
    public static final String NW_COMPASS_PORTAL_PROFILE_NAME = 'NWCompass Portal';
    public static final String NW_COMPASS_PORTAL_PERMISSION_SET_NAME = 'NWCompass Portal Permissions'; // need to delete
    public static final String NW_COMPASS_PORTAL_PERMISSION_SET_GROUP_NAME = 'NWCompassPortalGroup';
    public static final String DEFAULT_COUNTRY = 'US';
    public static final String HOUSEHOLD_POSTFIX = 'Household'; 
}